title: Navigation
description: Documentation for automating Shadowserver reports received via email

remote_theme: just-the-docs/just-the-docs
baseurl: "/shadowserver_email_automation"




sass:
  style: compressed
