title: Shadowserver CSIRT Toolkit
description: Documentation and tools for automating Shadowserver reports
theme: just-the-docs
baseurl: "/shadowserver_email_automation"

nav_sort: case_insensitive

# Sidebar navigation
nav:
  - Home: index.md
  - System Requirements: system-requirements.md
  - Installation & Bootstrapping: installation-and-environment-bootstrapping.md
  - Environment Variables Explained: environment-configuration.md
  - Shadowserver Report Ingestion - Usage & Flow: shadowserver-report-ingestion-usage-and-flow.md
  - Shadowserver Report Metadata Scraper: shadowserver-report-metadata-scraper.md
  - Organization-Based Shadowserver Report Generator: organization-based-shadowserver-report-generator.md
