title: Navigation
description: Documentation for automating Shadowserver reports received via email

remote_theme: just-the-docs/just-the-docs
baseurl: "/shadowserver_email_automation"

nav_sort: false

# Sidebar navigation (manually ordered)
nav:
  - 01 Home: index.md
  - 02 System Requirements: system-requirements.md
  - 03 Installation & Bootstrapping: installation-and-environment-bootstrapping.md
  - 04 Environment Variables Explained: environment-configuration.md
  - 05 Shadowserver Report Ingestion - Usage & Flow: shadowserver-report-ingestion-usage-and-flow.md
  - 06 Shadowserver Report Metadata Scraper: shadowserver-report-metadata-scraper.md
  - 07 Organization-Based Shadowserver Report Generator: organization-based-shadowserver-report-generator.md

sass:
  style: compressed
