title: Navigation
description: Documentation for automating Shadowserver reports received via email

remote_theme: just-the-docs/just-the-docs
baseurl: "/shadowserver_email_automation"


# Sidebar navigation (manually ordered)
nav:
  - 01 Home: index.md
  - 02 System Requirements: 02_system-requirements.md
  - 03 Installation & Bootstrapping: 03_installation-and-environment-bootstrapping.md
  - 04 Environment Variables Explained: 04_environment-configuration.md
  - 05 Shadowserver Report Ingestion - Usage & Flow: 05_shadowserver-report-ingestion-usage-and-flow.md
  - 06 Shadowserver Report Metadata Scraper: 06_shadowserver-report-metadata-scraper.md
  - 07 Organization-Based Shadowserver Report Generator: 07_organization-based-shadowserver-report-generator.md

sass:
  style: compressed
